#!/bin/bash

pacman -S --needed --noconfirm \
    switch-dev \
    switch-bzip2 \
    switch-curl \
    switch-ffmpeg \
    switch-flac \
    switch-freetype \
    switch-giflib \
    switch-glad \
    switch-glfw \
    switch-glm \
    switch-jansson \
    switch-libass \
    switch-libconfig \
    switch-libdrm_nouveau \
    switch-libexpat \
    switch-libfribidi \
    switch-libgd \
    switch-libjpeg-turbo \
    switch-libjson-c \
    switch-liblzma \
    switch-liblzo2 \
    switch-libmad \
    switch-libmikmod \
    switch-libmodplug \
    switch-libmpv \
    switch-libogg \
    switch-libopus \
    switch-libpcre2 \
    switch-libpng \
    switch-libsamplerate \
    switch-libsodium \
    switch-libtheora \
    switch-libtimidity \
    switch-libvorbis \
    switch-libvorbisidec \
    switch-libvpx \
    switch-libwebp \
    switch-libxml2 \
    switch-libzstd \
    switch-mbedtls \
    switch-mesa \
    switch-miniupnpc \
    switch-mpg123 \
    switch-ode \
    switch-oniguruma \
    switch-opusfile \
    switch-physfs \
    switch-pkg-config \
    switch-sdl2 \
    switch-sdl2_gfx \
    switch-sdl2_image \
    switch-sdl2_mixer \
    switch-sdl2_net \
    switch-sdl2_ttf \
    switch-smpeg2 \
    switch-tinyxml2 \
    switch-wslay \
    switch-zlib \
    switch-zziplib
